[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "visfeats"
dynamic = ["version"]
description = "A library for extracting global visual features"
readme = "README.md"
authors = [{ name = "Qian Chu", email = "qianchu99@gmail.com" }]
requires-python = ">=3.10"
dependencies = ["scikit-image"]

[project.optional-dependencies]
resmem = ["resmem"]
dev = ["resmem", "pytest", "pre-commit"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
local_scheme = "node-and-date"
