[metadata]
name = visfeats
version = 2026.10.07
description = A library for extracting global visual features
author = Qian Chu
author_email = qianchu99@gmail.com

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.6
install_requires =
    scikit-image

[options.packages.find]
where = src

[options.extras_require]
resmem =
    resmem
dev =
    pytest
    pre-commit